---

#
# AtoM
#

- name: "Build AtoM themes (make)"
  command: "{{ item.build_cmd }}"
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ atom_themes }}"
  become_user: "{{ atom_user }}"

#
# DRMC/Binder
#

# can't compile Drmc plugin as user www-data
# http://stackoverflow.com/questions/22152162/npm-cannot-install-dependencies-attempt-to-unlock-something-which-hasnt-been

- name: "Temporarily change ownership of DRMC plugin directory"
  file:
    path: "{{ atom_drmc_path }}"
    state: "directory"
    owner: "{{ ansible_ssh_user }}"
    recurse: yes
  when:
    "atom_drmc is defined and atom_drmc|bool"

- name: "Update npm"
  shell: "source scl_source enable rh-nodejs6 ; npm update"
  args:
    chdir: "{{ atom_drmc_path }}"
  when:
    "atom_drmc is defined and atom_drmc|bool"

- name: "Install npm local dependencies"
  npm:
    path: "{{ atom_drmc_path }}"
    state: "latest"
  when:
    "atom_drmc is defined and atom_drmc|bool"

# using --force option to ignore Error compiling ../../arDominionPlugin/css/main.less
- name: "Build DRMC"
  command: "grunt build --force"
  args:
    chdir: "{{ atom_drmc_path }}"
  when: "atom_drmc is defined and atom_drmc|bool"

- name: "Build docs"
  command: "make html"
  args:
    chdir: "{{ atom_drmc_path }}/docs"
  when: "atom_drmc is defined and atom_drmc|bool"
  become: "no"
  ignore_errors: "yes"

- name: "Restore ownership of site directory"
  file:
    path: "{{ atom_drmc_path }}"
    state: "directory"
    owner: "{{ atom_user }}"
    group: "{{ atom_group }}"
    recurse: yes
