---

- name: "Stop worker"
  become: yes
  service:
    name: "{{ atom_worker_service_name }}"
    state: "stopped"
  ignore_errors: "yes" # It could be not created yet

- name: "Install atom-worker service (systemd)"
  become: yes
  template:
    src: "lib/systemd/system/atom-worker.service"
    dest: "/lib/systemd/system/atom-worker.service"

- name: "Start and enable atom-worker service"
  become: yes
  service:
    name: "{{ atom_worker_service_name }}"
    state: "restarted"
    enabled: "yes"

#
# Apache FOP (including installation of Java)
#

- name: "Use FOP 2.1 in AtoM 2.3 or newer (Ubuntu 16.04)" 
  set_fact:
    fop_version: "2.1"
  tags:
    - "fop"

- name: "Install Apache FOP: unarchive"
  become: yes
  unarchive:
    src: "https://archive.apache.org/dist/xmlgraphics/fop/binaries/fop-{{ fop_version }}-bin.tar.gz"
    dest: "/usr/share"
    creates: "/usr/share/fop-{{ fop_version }}"
    copy: "no"
    owner: "root"
    group: "root"
  tags:
    - "fop"

- name: "Install Apache FOP: set up FOP_HOME"
  become: yes
  lineinfile:
    dest: "/etc/environment"
    line: "FOP_HOME=/usr/share/fop-{{ fop_version }}"
  tags:
    - "fop"

- name: "Install Apache FOP: symlink"
  become: yes
  file:
    src: "/usr/share/fop-{{ fop_version }}/fop"
    dest: "/usr/local/bin/fop"
    state: "link"
  tags:
    - "fop"
