---

- name: "Restart php-fpm"
  changed_when: True
  become: yes
  systemd:
    name: "php-fpm"
    state: "restarted"

- name: "Reload php-fpm"
  changed_when: True
  become: yes
  systemd:
    name: "php-fpm"
    state: "reloaded"

- name: "stat atom dir"
  stat:
    path: "/usr/share/nginx/atom"
  register: atom_dir

- name: "Clear sf_cache"
  become: yes
  shell: "php symfony cc"
  args:
    chdir: "{{ atom_path }}"
  become_user: "{{ atom_user }}"
  environment: "{{ atom_pool_php_envs }}"

- name: "Restart smbd"
  service:
    name: "smbd"
    state: "restarted"

- name: "Restart nmbd"
  service:
    name: "nmbd"
    state: "restarted"
